name = "homeventure"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "KNOCK_DATA"
id = "0626d0de949c442bbadcd158cd2afa14"
